# pygame screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SIDEBAR_WIDTH = 400

# obstacle constants
RECTANGLE_THICKNESS = 1
RECTANGLE_WIDTH = 80
RECTANGLE_SPEED = 20

# physics constants
GRAVITY = 40
BIRD_JUMP_ACCELERATION = -65
BIRD_ACCELERATION_DOWN = 6

# ai constants
NUM_START_BIRDS = 100

# colors
WHITE = (255, 255, 255)
